### ISSUE TITLE
Tredly-Host takes a while to install

### ISSUE THREAD

**Issue by nathanaherne** [tredly/tredly-host#10]
We realise that Tredly-Host takes a while to install. This is because Tredly-Host uses VIMAGE (FreeBSD network virtualization) so on top of installing all the code for Tredly, we also need to recompile the FreeBSD kernel to support VIMAGE. Depending on your hardware this can take a while. We are working to solve this:
- There will be a downloadable Tredly-Host virtual machine available at http://www.tredly.com soon

When FreeBSD 11 hits release status (VIMAGE is supposed to come as standard) Tredly will be updated to support this release and a kernel recompile will no longer be required.

We are also working on other ways to solve this issue (there are many)

**Comment by cmanns** [comment]
Can a kernel be distributed and fetched with a y/N option prior to building kernel. 

amd64 generic + VIMAGE only

**Comment by laurieodgers** [comment]
Some thoughts on saving disk space after a successful kernel compilation:

/boot/kernel.old can be removed after a successful compile
Turn off RACCT_DEFAULT_TO_DISABLED
Disable kernel debug symbols https://forums.freebsd.org/threads/32840/

**Comment by nathanaherne** [comment]
To clarify further, disable any kernel modules not required for Tredly.

**Comment by pointybeard** [comment]
Moved to https://github.com/tredly/tredly/issues/46
