### ISSUE TITLE
Wiki referenced in README appears to not exist

### ISSUE THREAD

**Issue by yarwelp** [tredly/tredly-host#24]
README refers to https://github.com/tredly/tredly-host/wiki/Tredly-Overview

Attempting to access that page redirects to the repository root.

It seems that the wiki does not exist, at least not to the public.

**Comment by pointybeard** [comment]
Thanks for spotting that. It should be linking to our Tredly Docs website - http://www.tredly.com/docs/?cat=4

I'll get that sorted.
