### ISSUE TITLE
Add ability to redirect ports to another port.

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-host#25]
For instance. Let's say I have a python project running as a deploy user.

That user is not allowed to allocate port 80 since it's not root. Hence, I would need to have the nginx reverse_proxy talk with the port I specify in the Tredlyfile.

Maybe it could be like this:

url1=test.example.com

httpInPort=8080

tcpInPort=8080

Tredly would then know to configure nginx to forward to port 8080 in the jail.

Even though using jails and containers is pretty secure this would add an additional bit of security.

**Comment by nathanaherne** [comment]
Good idea dinapappor

This could be implemented by adding url1Port to URL configuration section of Tredlyfile. Someone from Vuid/Tredly will be along soon to put this on the list for the next version (won't be far away).

**Comment by pointybeard** [comment]
Moved to https://github.com/tredly/tredly/issues/42
