### ISSUE TITLE
Running Tredly-host on virtual box using Wifi adapter does not work

### ISSUE THREAD

**Issue by pointybeard** [tredly/tredly-host#27]
Currently it is not possible to run Tredly locally when the host machine is using a Wifi network adapter.

**Comment by laurieodgers** [comment]
Virtualbox has a problem where WIFI adapters cannot be placed into promiscuous mode. This affects Tredly's ability to bridge traffic between the local public LAN and the bridge0 (public) interface. As a result of this, containers with public IP addresses running on WIFI will not have network connectivity past the host.

This is not an issue for ethernet cable connected Virtualbox VMs. Note that cable connected VMs require the bridged adapter to have promiscuous mode "Allow All" enabled within Virtualbox.

**Comment by pointybeard** [comment]
Moved to https://github.com/tredly/tredly/issues/41
