### ISSUE TITLE
Confusion about ssl certificates/bug

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-host#28]
I don't understand how the ssl certificates works. Or more rather the placements.
I have tried this:

Defining an urlcert like so:

```
url1=something.domain.tld
url1Cert=star.domain.tld
```

In the same folder as the Tredlyfile I have the directory `star.domain.tld` containing server.key and server.crt. I push the container, the `server.key` and `server.crt` get's uploaded to `/usr/local/etc/nginx/ssl/default/star.domain.tld/star.domain.tld/`. 

nginx config looks like this

```
server {
    listen 192.168.88.254:443 ssl;
    location / {
        include proxy_pass/http_https;
        proxy_bind 192.168.88.254;
        proxy_pass https://https-something.domain.tld;
    }
    server_name something.domain.tld;
    ssl on;
    ssl_certificate ssl/default/star.domain.tld/server.crt;
    ssl_certificate_key ssl/default/star.domain.tld/server.key;
}
```

As you can see the path referenced in nginx does not align with the directories being made by tredly for the ssl certificates.

Am I doing something wrong or is this a bug?

**Comment by laurieodgers** [comment]
Hi dinapappor
Thanks for posting this. Yes this certainly is a bug - I can reproduce this with the steps posted above.

I have applied a fix which will be in the 0.10.2 release later today. 

Please also note that in 0.10.2 your url1Cert above will need to start with a / to indicate that the cert is coming from the container directory or tredly will throw an error and refuse to build the container. IE:
url1Cert=/star.domain.tld
