### ISSUE TITLE
Ports doesnt get forwarded

### ISSUE THREAD

**Issue by dinapappor** [tredly/tredly-host#47]
While the reverse proxy feature with nginx works great I am having troubles getting regular destination nat to work.

I can see that in the container the ports get's added without a problem, it's added 3 times (port 13222) for three different tables, but I can't find the tables defined anywhere.

```
0100 allow log tcp from table(2) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00200 allow log tcp from table(3) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00300 allow log tcp from table(1) to 10.99.219.69 dst-port 13222 in via vnet0 setup keep-state
00400 allow log tcp from 10.99.219.69 to any dst-port 80 out via vnet0 setup keep-state
00500 allow log tcp from 10.99.219.69 to any dst-port 443 out via vnet0 setup keep-state
00600 allow log udp from 10.99.219.69 to any dst-port 53 out via vnet0 keep-state
00700 allow log tcp from 10.99.219.69 to any dst-port 80,5672 out via vnet0 setup keep-state
00800 allow log udp from 10.99.219.69 to any dst-port 53 out via vnet0 keep-state
00900 allow log udp from 10.99.219.69 to 10.99.255.254 dst-port 53 out via vnet0 keep-state
01000 allow log udp from 10.99.219.69 to 10.99.219.69 via vnet0 keep-state
01100 allow log tcp from 10.99.219.69 to 10.99.219.69 via vnet0 setup keep-state
01200 allow log ip from any to any via lo0
65535 deny ip from any to any
```

These rules are not in /usr/local/etc/ipfw.rules in the container. There's just a bash shebang in there.

On the tredly-host I am seeing no mention of port 13222. I've examined the `ipfw list` command as well as all the ipfw.\* files.

From inside the container I can reach the service (in this case ssh) with that port without a problem.
Trying to reach the container from the tredly-host with `ssh -luser -p13222 containerip` fails with a timeout. And the same happens from the outside. 

SSH listening on port 13222 inside the container:

```
root@project-microservice:/ # netstat -an
netstat: kvm not available: /dev/mem: No such file or directory
Active Internet connections (including servers)
Proto Recv-Q Send-Q Local Address          Foreign Address        (state)
tcp4       0      0 *.13222                *.*                    LISTEN
tcp6       0      0 *.13222                *.*                    LISTEN
```

I have the following ports defined in the Tredlyfile:

```
# The following is for SSH into this instance to allow for ansible to ssh into this container and do hot code reloads.
tcpInPort=13222

# Needed to install packages
tcpOutPort=80

# Needed for connections to RabbitMQ
tcpOutPort=5672

# Needed for DNS queries.
udpOutPort=53
```

I am running my own package repo and I wont need https and ftp outbound. The packages get's installed fine.

I am also seeing that TSO doesn't get shut off by default. I think the issue is that since `net.inet.tcp.tso` is a read/write tunable it needs to go into /etc/sysctl.conf or else it wont get honored.

Loader tunables (The ones that can only be set at boot) goes into /boot/loader.conf and read/write tunables (the ones that can be changed anytime) goes into /etc/sysctl.conf.

If I can provide more information in order to debug these problems let me know. I would be happy to help.

**Comment by laurieodgers** [comment]
Thanks for the feedback!

Have you tried whitelisting the hosts/ranges attempting to connect to your ssh container with `ipv4Whitelist=` in your tredlyfile? And does your container have a containerGroup?

Currently the ipfw table files within the container aren't populated (will be rectified soon) but the LIVE ipfw tables are populated - these can be seen with `ipfw table <number> list` run within the container.

With respect to the TSO setting in loader/sysctl - I have added this option to the sysctl file as well as the boot loader, but since we have literally done a release in the past hour, it won't make it in until next release.

**Comment by dinapappor** [comment]
Hi, thanks for the quick reply.  I just tried with containergroup and ipv4Whitelist=0.0.0.0/0 in separate runs. As well as setting both options at the same time.

I can now ssh into the container from the tredly-host but not from outside the tredly-host. This is regardless of cointainergroup but ipv4whitelist needs to be set.

**Comment by laurieodgers** [comment]
Can you please show me the contents of the ipfw tables within the container by running the following commands within the container:
`ipfw table 1 list`
`ipfw table 2 list`
`ipfw table 3 list`

These tables relate as follows:
1. whitelist for containergroup members
2. whitelist for partition members 
3. whitelist for container (comes from ipv4Whitelist= in your tredlyfile)

With respect to the firewall rules, the logic within tredly is as follows:
`if a whitelist is set in the tredlyfile, allow that whitelist to communicate in on tcp/udpinports`
`else if a containergroup is set in the tredlyfile, allow members of that containergroup to communicate in on tcp/udpinports`
`else allow anyone to communicate in on tcp/udpinports`

What is the contents of /usr/local/etc/ipfw.layer4 on the host? Its possible that its a forwarding problem not a firewall problem.

**Comment by dinapappor** [comment]
Hi, sorry for the late reply

But here goes:

```
root@project-microservice:/ # ipfw table 1 list
10.99.0.114/32 0
10.99.50.135/32 0
root@project-microservice:/ # ipfw table 2 list
root@project-microservice:/ # ipfw table 3 list
0.0.0.0/0 0
```

(There was no output for table number 2.)

`/usr/local/etc/ipfw.layer4`:

```
root@tredly02:/home/tredly # cat /usr/local/etc/ipfw.layer4 
#!/usr/bin/env bash

. /usr/local/etc/ipfw.vars

# Configure NAT and port redirection on the Tredly-Host external IP
ipfw -q nat 1 config ip $eip same_ports log \
redirect_port tcp $p7ip:80 80 \
redirect_port tcp $p7ip:443 443 \
```

**Comment by laurieodgers** [comment]
Yes definitely looks like a port forwarding bug. The output from /usr/local/etc/ipfw.layer4 should include port 13222 to the ip address of your container. As a workaround you can add an extra redirect_port line in the format:
`redirect_port tcp <ip address of container>:13222 13222` 

to the end of the file, then execute it with sh:

`sh /usr/local/etc/ipfw.layer4`

and the forward should work.

I'll raise this to critical and a fix will be with the next release.

**Comment by dinapappor** [comment]
Yes that worked, thank you! :)

**Comment by pointybeard** [comment]
This discussion has been movied to the tredly/tredly issue tracker https://github.com/tredly/tredly/issues/36
